GET http://localhost:8080/devops_starter_war_exploded/api/person/all

###
POST http://localhost:8080/devops_starter_war_exploded/api/person
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"name": "Nick", "age": 28}

###
PUT http://localhost:8080/devops_starter_war_exploded/api/person/4
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"name": "Mark", "age": 7}